# Create OSCARS / EOSC Vocabulary

## Import

In [1]:
import pandas as pd
import numpy as np
from rdflib import Graph, URIRef, Literal
from rdflib.namespace import RDF, SKOS, DC, OWL

## Create vocabulary graph

Define vocabulary graph, declare concept scheme, and add metadata.

In [2]:
voc = Graph()
namespace = "https://vocabs.sshopencloud.eu/vocabularies/oscars/"
concept_scheme = URIRef(namespace)
voc.add((concept_scheme, RDF.type, SKOS.ConceptScheme))
# title
voc.add((concept_scheme, SKOS.prefLabel, Literal("OSCARS / EOSC Vocabulary", lang='en')))
voc.add((concept_scheme, DC.title, Literal("OSCARS / EOSC Vocabulary", lang='en')))
# creator
voc.add((concept_scheme, DC.creator, Literal("OSCARS Glossaries Task Force", lang='en')))
# description
voc.add((concept_scheme, DC.description, Literal("The vocabulary defines concepts frequently used within the OSCARS project, the five science clusters that initiated the project, and the wider EOSC ecosystem.\nBoth technical and organisational terms are covered. Some of the definitions and notes are based on work of previous INFRA/EOSC projects funded under Horizon Europe.\nThe SSH Open Cluster provided the technical expertise.", lang='en')))
# language
voc.add((concept_scheme, DC.language, Literal("English", lang='en')))
# publisher
voc.add((concept_scheme, DC.publisher, Literal("Trust-IT (on behalf of OSCARS)", lang='en')))
# license
voc.add((concept_scheme, DC.rights, Literal("https://opendatacommons.org/licenses/by/1.0/")))
# subjects
voc.add((concept_scheme, DC.subject, Literal("Open Science", lang='en')))
voc.add((concept_scheme, DC.subject, Literal("research infrastructure", lang='en')))
voc.add((concept_scheme, DC.subject, Literal("EOSC governance", lang='en')))
# relation
voc.add((concept_scheme, DC.relation, URIRef("https://oscars-project.eu/")))
voc.add((concept_scheme, DC.relation, URIRef("https://science-clusters.eu/")))
# sources
voc.add((concept_scheme, DC.source, Literal("EOSC Future Glossary 2024", lang='en')))
voc.add((concept_scheme, DC.source, Literal("EOSC Glossary 2020", lang='en')))
voc.add((concept_scheme, DC.source, Literal("EOSC Federation Handbook", lang='en')))
# version
voc.add((concept_scheme, OWL.versionInfo, Literal("1.0.0")))

Load vocabulary data from CSV.

In [3]:
# Load vocabulary data from CSV
names=["term_name", "acronym", "pending_discussion", "definition", "project", "source_indications", "date", "select", "to_be_discussed", "reject", "final_decision", "status", "comments", "uri", "prefLabel", "altLabel", "broader", "original_definition", "note", "example", "exactMatch", "closeMatch"]
df = pd.read_csv('data.csv')
df.columns = names
df = df.drop(df.index[[0, 1]]).reset_index(drop=True) # Drop first two rows and reset index
df = df[df["final_decision"] == "select"]
columns_to_drop = ["pending_discussion", "date", "select", "to_be_discussed", "reject", "status", "final_decision", "comments", "original_definition"]
df = df.drop(columns=columns_to_drop)

In [4]:
df = df.map(lambda x: x.strip() if isinstance(x, str) else x)

In [5]:
df

,term_name,acronym,definition,project,source_indications,uri,prefLabel,altLabel,broader,note,example,exactMatch,closeMatch
0,access,NaN,protocol for availability of research data and...,"OSCARS Glossary TaskForce 2026, based on sever...",NaN,Access,access,NaN,NaN,The ESFRI report distinguishes a diversity of ...,"Listed in the Access Charter: machine time, c...",NaN,NaN
1,administrative metadata,NaN,metadata​ necessary to allow the proper manage...,EOSC Glossary September 2020,"ISO/TR 14873:2013, modified –– reference to me...",AdministrativeMetadata,administrative metadata,NaN,metadata,Administrative metadata can be categorised as ...,NaN,NaN,NaN
2,Authentication and Authorisation Infrastructure,AAI,service (or distributed set of services) which...,EOSCFuture project glossary,NaN,AuthenticationAndAuthorisationInfrastructure,Authentication and Authorisation Infrastructure,AAI,service,NaN,NaN,NaN,NaN
3,certified repository,NaN,digital data archive that has been evaluated a...,"OSCARS Glossary TaskForce 2026, based on sever...",NaN,CertifiedRepository,certified repository,NaN,repository,"Repository certification, such as CoreTrustSea...",NaN,NaN,NaN
4,competence centre,NaN,virtual hub dedicated to fostering research ex...,https://oscars-project.eu/clusters-open-scienc...,NaN,CompetenceCentre,competence centre,NaN,NaN,Specifically in the context of OSCARS: communi...,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
90,training resource,NaN,any resource – including print and non-print m...,EOSCFuture project glossary,NaN,TrainingResource,training resource,NaN,resource,If a training resource is used in a training e...,NaN,NaN,NaN
91,TRUST principles,NaN,set of guidelines to make ​digital repositorie...,EOSC Glossary September 2020,"Lin, D., Crabtree, J., Dillo, I., Downs, R. R....",TrustPrinciples,TRUST principles,NaN,trusted digital repository,NaN,NaN,NaN,NaN
92,trusted digital repository,TDR,repository​ certfied according to ISO standard...,EOSC Glossary September 2020;,EOSC Glossary September 2020,TrustedDigitalRepository,trusted digital repository,trustworthy digital repository | TDR,certified repository,NaN,NaN,NaN,NaN
93,virtual research environment,VRE,environment that allows a researcher to provid...,OSCARS D2.2 - Service Composability Report,NaN,VirtualResearchEnvironment,virtual research environment,VRE,NaN,NaN,NaN,NaN,NaN
94,workflow,NaN,well-defined series of tasks,OSCARS D2.1 - Clusters' Services and Data Sour...,NaN,Workflow,workflow,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 95 entries, 0 to 94
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   term_name           95 non-null     object
 1   acronym             16 non-null     object
 2   definition          95 non-null     object
 3   project             94 non-null     object
 4   source_indications  33 non-null     object
 5   uri                 95 non-null     object
 6   prefLabel           95 non-null     object
 7   altLabel            19 non-null     object
 8   broader             52 non-null     object
 9   note                31 non-null     object
 10  example             8 non-null      object
 11  exactMatch          3 non-null      object
 12  closeMatch          0 non-null      float64
dtypes: float64(1), object(12)
memory usage: 10.4+ KB

## Check duplicate URIs

In [7]:
df[df.duplicated(subset="uri", keep=False)]

Empty DataFrame
Columns: [term_name, acronym, definition, project, source_indications, uri, prefLabel, altLabel, broader, note, example, exactMatch, closeMatch]
Index: []

## Check broader term consistency

In [8]:
for index, row in df.iterrows():
    broader = row["broader"]
    if pd.notna(broader):
        if broader not in df["prefLabel"].values:
            print(index, row["prefLabel"], "->", broader, "🚨")

18 domain repository -> research data repository | thematic service 🚨

## Create SKOS concepts

In [9]:
for _, row in df.iterrows():

    uri = row["uri"]
    uri = uri.strip()
    uri = URIRef(namespace + uri)
    voc.add((uri, SKOS.inScheme, concept_scheme))
    voc.add((uri, RDF.type, SKOS.Concept))

    if pd.notna(row["definition"]):
        definition = row["definition"]
        voc.add((uri, SKOS.definition, Literal(definition, lang="en")))

    if pd.notna(row["project"]):
        source = row["project"]
        voc.add((uri, DC.source, Literal(source, lang='en')))

    if pd.notna(row["source_indications"]):
        source = row["source_indications"]
        voc.add((uri, DC.source, Literal(source, lang='en')))

    prefLabel = row["prefLabel"]
    voc.add((uri, SKOS.prefLabel, Literal(prefLabel, lang="en")))

    if pd.notna(row["altLabel"]):
        altLabel = row["altLabel"]
        if "|" in altLabel:
            altLabels = altLabel.split("|")
            for label in altLabels:
                label = label.strip()
                voc.add((uri, SKOS.altLabel, Literal(label, lang="en")))
        else:
            voc.add((uri, SKOS.altLabel, Literal(altLabel, lang="en")))

    if pd.notna(row["broader"]):
        if "|" in row["broader"]:
            broader_uris = row["broader"].split("|")
            for broader_uri in broader_uris:
                broader_uri = broader_uri.strip()
                matching_row = df.loc[df.iloc[:, 6] == broader_uri]
                if not matching_row.empty:
                    value = matching_row.iloc[0, 5]
                    value = namespace + value
                    voc.add((uri, SKOS.broader, URIRef(value)))
        else:
            broader_uri = row["broader"].strip()
            matching_row = df.loc[df.iloc[:, 6] == broader_uri]
            if not matching_row.empty:
                value = matching_row.iloc[0, 5]
                value = namespace + value
                voc.add((uri, SKOS.broader, URIRef(value)))
    else:
        voc.add((uri, SKOS.topConceptOf, concept_scheme))

    if pd.notna(row["note"]):
        note = row["note"]
        if "|" in note:
            note = note.split("|")
            for element in note:
                element = element.strip()
                voc.add((uri, SKOS.note, Literal(element, lang="en")))
        else:
            voc.add((uri, SKOS.note, Literal(note, lang="en")))

    if pd.notna(row["example"]):
        example = row["example"]
        voc.add((uri, SKOS.example, Literal(example, lang="en")))

voc.serialize(destination="oscars-eosc.ttl")